# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ee0a410bf78b3ca6bffe06895ee578930bd13b697ba0a2269fd2d9ba43b1c76b1bf0b38b4a80fbbbc3b85d6bd57aa71c13d7735b2b176fa92080ddca55600df

test:
  secret_key_base: 8d9319657424740628f350897abd29a9c38fd6bed7e23eb28715973f76a507e5dda75e19e65a79b0d46a2437d095ba9704fd26567ac41be40e304ede359b1dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
